### ISSUE TITLE
Investigate DLS in MPEG2 frames from mot-encoder / toolame.

### ISSUE THREAD

**Issue by nickpiggottwork** [smallscaledab/small-scale-dab#8]
DLS doesn't appear to be inserting correctly into MPEG2 streams provided to the mux. This could be a toolame or mot-encoder problem.

It would be useful to get a grab of some faulty frames, if anyone's got any. (@simonwhill ?)

**Comment by mpbraendli** [comment]
@basicmaster is currently working on a better interconnection between mot-encoder and the encoder, which would change from the current "mot-encoder sends data when it feels like" to "the encoder asks mot-encoder data when it needs it". This will make the whole PAD more flexible.

For this ticket in particular, are you talking about a fault in the current versions ?

**Comment by nickpiggottwork** [comment]
It's not clear yet if it's a fault in the code, or a fault in the configuration.

I think @simonwhill can get DLS working when he's piping from an MPEG2 file, but not when it's encoding live?

**Comment by rashrf** [comment]
If it is the Odroid C1 (black) then it is an configuration issue - I didn't copy the latest scripts or binary to them. This shouldn't happen on the U3 encoder. The latter has a simple means of displaying DLS via a text file which is read by mot-enocder, and outputs to fifo. While on the subject of the C1, I am becoming increasingly convinced that these were a bad choice because some have been failing on soak test. They were a last minute reaction to the surprising number of services in the trial because they are cheaper....guess what - buy cheap, pay twice! We don't have enough U3s to cover all of the services, but I might be able to procure some more next week.

**Comment by nickpiggottwork** [comment]
That sounds like a potential config issue then. I expect Simon can confirm which ones he's got.

**Comment by nickpiggottwork** [comment]
I'm going to close this issue because I think we ascertained that it was a config issue.
